// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/order/order.proto

package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CustomerID           string   `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	LineItems            []string `protobuf:"bytes,3,rep,name=lineItems,proto3" json:"lineItems,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	PaymentStatus        string   `protobuf:"bytes,5,opt,name=paymentStatus,proto3" json:"paymentStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCreated) Reset()         { *m = OrderCreated{} }
func (m *OrderCreated) String() string { return proto.CompactTextString(m) }
func (*OrderCreated) ProtoMessage()    {}
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_86e6eefb677177a4, []int{0}
}
func (m *OrderCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreated.Unmarshal(m, b)
}
func (m *OrderCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreated.Marshal(b, m, deterministic)
}
func (dst *OrderCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreated.Merge(dst, src)
}
func (m *OrderCreated) XXX_Size() int {
	return xxx_messageInfo_OrderCreated.Size(m)
}
func (m *OrderCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreated.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreated proto.InternalMessageInfo

func (m *OrderCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *OrderCreated) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *OrderCreated) GetLineItems() []string {
	if m != nil {
		return m.LineItems
	}
	return nil
}

func (m *OrderCreated) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderCreated) GetPaymentStatus() string {
	if m != nil {
		return m.PaymentStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderCreated)(nil), "order.OrderCreated")
}

func init() { proto.RegisterFile("pkg/proto/order/order.proto", fileDescriptor_order_86e6eefb677177a4) }

var fileDescriptor_order_86e6eefb677177a4 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x2f, 0x4a, 0x49, 0x2d, 0x82, 0x90, 0x7a, 0x60, 0x11,
	0x21, 0x56, 0x30, 0x47, 0x69, 0x06, 0x23, 0x17, 0x8f, 0x3f, 0x88, 0xe5, 0x5c, 0x94, 0x9a, 0x58,
	0x92, 0x9a, 0x22, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4,
	0xe4, 0xe9, 0x22, 0x24, 0xc7, 0xc5, 0x95, 0x5c, 0x5a, 0x5c, 0x92, 0x9f, 0x9b, 0x5a, 0xe4, 0xe9,
	0x22, 0xc1, 0x04, 0x16, 0x47, 0x12, 0x11, 0x92, 0xe1, 0xe2, 0xcc, 0xc9, 0xcc, 0x4b, 0xf5, 0x2c,
	0x49, 0xcd, 0x2d, 0x96, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x89, 0x70, 0xb1,
	0x16, 0x14, 0x65, 0x26, 0xa7, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x30, 0x05, 0x41, 0x38, 0x42, 0x2a,
	0x5c, 0xbc, 0x05, 0x89, 0x95, 0xb9, 0xa9, 0x79, 0x25, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x12,
	0xac, 0x60, 0x63, 0x51, 0x05, 0x93, 0xd8, 0xc0, 0x0e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0xe8, 0x2f, 0x84, 0xc7, 0x00, 0x00, 0x00,
}
